services:
  wallet-db:
    image: postgres:15
    container_name: wallet-db
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - wallet_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wallet_user", "-d", "wallet_db"]
      interval: 1s
      timeout: 5s
      retries: 5

  wallet-test-db:
    image: postgres:15
    container_name: wallet-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: wallet_test_db
    ports:
      - "5433:5432"
    volumes:
      - test_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
          test: [ "CMD", "test_pg_isready", "-U", "test_user", "-d", "test_db" ]
          interval: 1s
          timeout: 5s
          retries: 5

  wallet-service:
    build:
      context: ./  # Контекст сборки
    container_name: wallet-service
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.env:/app/config/config.env
    depends_on:
      wallet-db:
        condition: service_healthy
    restart: on-failure

volumes:
  wallet_data:
  test_data:
